# START Service
apiVersion: v1
kind: Service
metadata:
  name: django-web-svc
  labels:
    app: django
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    name: django
    tier: frontend
# END SERVICE

---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: django1
  name: django-pv1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /home/docker/FirstProject
    type: ""
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: default
    name: django-pv-claim6
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-pv-claim6
  labels:
    app: django
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: django-pv1 # mount to this persistent volume
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: django-web
  labels:
    app: django
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: django
        tier: frontend
    spec:
      containers:
      - name: django-web
        image: martialsoh/tech_website_image:1.6
        ports:
        - containerPort: 8000
          name: django
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: password
          - name: POSTGRES_DB
            value: 'postgres'
          - name: DATABASE_URL
            value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: django-secret-key
                key: secret_key
        volumeMounts:
        - name: django-persistent-storage
          mountPath: /FirstProject
      volumes:
      - name: django-persistent-storage
        persistentVolumeClaim:
          claimName: django-pv-claim6