#buid compose-start
version: '3.7'

services:

  db_migrate:
    image: tech_website_image:latest
    command: python3 manage.py migrate
    volumes:
      - ./:/app/:rw,cached
    env_file:
    - .env
    environment:
      - POSTGRES_DB=$DATABASE_NAME
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_HOST=$DATABASE_HOST
    depends_on:
      - postgres

  postgres:
    image: postgres:13.4
    env_file:
    - .env
    environment:
      - POSTGRES_DB=$DATABASE_NAME
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  website:
    image: tech_website_image:latest
    command: python3 manage.py runserver 0.0.0.0:8000
    restart: always
    env_file:
    - .env
    environment:
      PYTHONUNBUFFERED: 1
      DATABASE_URL: postgres://$DATABASE_USER:$DATABASE_PASSWORD@$DATABASE_HOST:$DATABASE_PORT/$DATABASE_NAME
    volumes:
      - ./:/app/:rw,cached
    depends_on:
      - db_migrate
    ports:
      - "8000:8000"

volumes:
  db-data: